baseURL = "https://uprooted.unc.edu"
defaultContentLanguage = "en"
copyright = ""
title = "Uprooted: Venezuelan Families Flee to Colombia"
themesDir = "../.."
enableInlineShortcodes = "true"

[languages]
  [languages.en]
    title = "Uprooted: Venezuelan Families Flee to Colombia"
    weight = "1"
    [languages.en.params]
      
  [languages.es]
    title = ""
    weight = "2"
    [languages.es.params]
      
      [languages.es.params.navigation]
        help = "Ayuda"
      


[params]
  google_analytics_id = ""

  [params.homepage_meta_tags]
    meta_description = "Uprooted is a multimedia journalism project produced by the UNC School of Media and Journalism"
    meta_og_title = "Uprooted: Venezuelan Families Flee to Colombia"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = "@"
    meta_twitter_creator = "@"
  [params.navigation]
    help = "Help"

[[menu.main]]
	name = "Story 1"
	url = "/story1/"
    weight = 1

[[menu.main]]
    name = "Story 2"
    url = "/story2/"
    weight = 2

[[menu.main]]
    name = "Story 3"
    url = "/story3/"
    weight = 3

[[menu.main]]
    name = "Story 4"
    url = "/story4/"
    weight = 4 

[[menu.main]]
    name = "Story 5"
    url = "/story5/"
    weight = 5

[[menu.main]]
    name = "Interactive"
    url = "/interactive/"
    weight = 6

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 7

[permalinks]
  post = "/:slug"
  pages = "/:filename"




